name: unigen
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.6.4=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py312h06a4308_0
  - python=3.12.9=h5148396_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py312h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.2.1
      - accelerate==1.1.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - albucore==0.0.24
      - albumentations==2.0.8
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - argcomplete==3.6.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrdict==2.0.1
      - attrs==25.3.0
      - av==14.3.0
      - beautifulsoup4==4.13.4
      - binpacking==1.5.2
      - bitsandbytes==0.45.5
      - boto==2.49.0
      - boto3==1.38.23
      - botocore==1.38.23
      - brotli==1.1.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - cfgv==3.5.0
      - charset-normalizer==3.4.1
      - click==8.2.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.1
      - cpm-kernels==1.0.11
      - crcmod==1.7
      - cryptography==43.0.3
      - cycler==0.12.1
      - cython==3.1.2
      - dacite==1.7.0
      - datasets==3.4.1
      - decorator==5.2.1
      - decord==0.6.0
      - deepspeed==0.16.5
      - deprecated==1.2.18
      - diffusers==0.32.2
      - dill==0.3.8
      - distlib==0.4.0
      - distro==1.9.0
      - dists-pytorch==0.1
      - dnspython==2.7.0
      - easydict==1.13
      - einops==0.8.1
      - executing==2.2.0
      - external==2.0
      - facexlib==0.3.0
      - fastapi==0.115.12
      - fasteners==0.19
      - ffmpy==0.6.0
      - fiftyone==1.5.2
      - fiftyone-brain==0.21.2
      - fiftyone-db==1.1.7
      - filelock==3.18.0
      - filterpy==1.4.5
      - flatbuffers==25.2.10
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - ftfy==6.3.1
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gcs-oauth2-boto-plugin==3.2
      - gdown==5.2.0
      - glob2==0.7
      - google-apitools==0.5.32
      - google-auth==2.17.0
      - google-auth-httplib2==0.2.0
      - google-reauth==0.1.1
      - gradio==5.27.1
      - gradio-client==1.9.1
      - gradio-imageslider==0.0.20
      - graphql-core==3.2.6
      - groovy==0.1.2
      - grpcio==1.71.0
      - gsutil==5.33
      - h11==0.16.0
      - h2==4.2.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - hpack==4.1.0
      - httpcore==1.0.9
      - httplib2==0.20.4
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - humanize==4.12.3
      - hypercorn==0.17.3
      - hyperframe==6.1.0
      - icecream==2.1.8
      - identify==2.6.15
      - idna==3.10
      - imagehash==4.3.2
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - inflate64==1.0.1
      - iniconfig==2.3.0
      - insightface==0.7.3
      - iopath==0.1.10
      - ipdb==0.13.13
      - ipython==9.0.2
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.6
      - jiter==0.12.0
      - jmespath==0.10.0
      - joblib==1.5.1
      - json-repair==0.54.1
      - jsonlines==4.0.0
      - kaleido==0.2.1
      - kiwisolver==1.4.8
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - lightning==2.5.1.post0
      - lightning-utilities==0.14.2
      - llvmlite==0.45.1
      - lmdb==1.7.5
      - loguru==0.7.3
      - lpips==0.1.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - mmcv-full==1.7.2
      - mmengine==0.10.7
      - mmsegmentation==1.2.2
      - modelscope==1.32.0
      - mongoengine==0.29.1
      - monotonic==1.6
      - motor==3.6.1
      - mpmath==1.3.0
      - ms-swift==3.10.1
      - msgpack==1.1.0
      - multidict==6.2.0
      - multiprocess==0.70.16
      - multivolumefile==0.2.3
      - narwhals==1.41.0
      - networkx==3.4.2
      - ninja==1.11.1.3
      - nltk==3.9.2
      - nodeenv==1.9.1
      - numba==0.62.1
      - numpy==2.2.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.4.127
      - oauth2client==4.1.3
      - omegaconf==2.3.0
      - onnx==1.19.1
      - onnxruntime==1.21.0
      - open-clip-torch==2.31.0
      - openai==2.8.1
      - openai-clip==1.0.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opencv-transforms==0.0.6
      - optimum-quanto==0.2.7
      - orjson==3.10.18
      - oss2==2.19.1
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - peft==0.15.0
      - pexpect==4.9.0
      - pillow==11.1.0
      - platformdirs==4.3.8
      - plotly==6.1.1
      - pluggy==1.6.0
      - portalocker==3.2.0
      - pprintpp==0.4.0
      - pre-commit==4.4.0
      - prettytable==3.16.0
      - priority==2.0.0
      - prodigyopt==1.1.2
      - prompt-toolkit==3.0.50
      - propcache==0.3.0
      - protobuf==6.30.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py7zr==0.22.0
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybcj==1.0.6
      - pycocotools==2.0
      - pycparser==2.22
      - pycryptodome==3.23.0
      - pycryptodomex==3.23.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydash==8.0.5
      - pydub==0.25.1
      - pygments==2.19.1
      - pyiqa==0.1.14.1
      - pymongo==4.9.2
      - pyopenssl==24.2.1
      - pyparsing==3.2.1
      - pyppmd==1.1.1
      - pysocks==1.7.1
      - pytest==9.0.1
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.3
      - python-multipart==0.0.20
      - pytorch-fid==0.3.0
      - pytorch-lightning==2.5.1
      - pytz==2025.1
      - pyu2f==0.1.5
      - pywavelets==1.9.0
      - pyyaml==6.0.2
      - pyzstd==0.17.0
      - qwen-vl-utils==0.0.8
      - rarfile==4.2
      - regex==2024.11.6
      - requests==2.32.3
      - retry-decorator==1.1.1
      - retrying==1.3.4
      - rich==14.0.0
      - rouge==1.0.1
      - rsa==4.7.2
      - rtree==1.4.0
      - ruff==0.11.13
      - s3transfer==0.13.0
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scepter==1.4.0
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - simplejson==3.20.2
      - simsimd==6.5.3
      - six==1.17.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.7
      - sse-starlette==0.10.3
      - sseclient-py==1.8.0
      - stack-data==0.6.3
      - starlette==0.46.2
      - strawberry-graphql==0.270.2
      - stringzilla==4.2.3
      - structlog==25.2.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - texttable==1.7.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.6.0
      - tifffile==2025.3.30
      - tiktoken==0.12.0
      - timm==1.0.15
      - tokenizers==0.15.2
      - tomlkit==0.13.3
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - torchinfo==1.8.0
      - torchmetrics==1.7.0
      - torchsde==0.2.6
      - torchvision==0.21.0+cu118
      - torchviz==0.0.3
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trampoline==0.1.2
      - transformers==4.37.2
      - transformers-stream-generator==0.0.5
      - triton==3.2.0
      - trl==0.24.0
      - typer==0.16.0
      - typing-extensions==4.13.2
      - tzdata==2025.1
      - tzlocal==5.3.1
      - universal-analytics-python3==1.1.1
      - urllib3==2.3.0
      - uvicorn==0.34.3
      - virtualenv==20.35.4
      - voxel51-eta==0.14.0
      - wcwidth==0.2.13
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - wsproto==1.2.0
      - xformers==0.0.29.post3
      - xmltodict==0.14.2
      - xxhash==3.5.0
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.18.3
      - zipp==3.21.0
      - zstandard==0.25.0
      
